### PR TITLE
Change iCub in Gazebo port prefix from /icubGazeboSim to /icubSim

### PR DESCRIPTION
**Pull request by traversaro**
Ref https://github.com/robotology/icub-gazebo/issues/8

### CODE REVIEW

**Comment by traversaro** [comment]
Do not merge until https://github.com/robotology/icub-gazebo/pull/53 is merged.

**Comment by rlober** [comment]
Thanks @traversaro ! I will merge merge as soon as we get a few other little issues fixed.

**Comment by traversaro** [comment]
We merged the PR https://github.com/robotology/icub-gazebo/issues/8, so feel free to merge this PR when you want.

**Comment by traversaro** [comment]
I think this is not relevant anymore, feel free to re-open otherwise.

**Pull request closed without merging**
